"""
Synthetic demo assets and a simulated maintenance history.

OFF BY DEFAULT, and that is the whole point. The fleet imported from
`Template_Import_Aset_RAMCES.xlsx` is REAL, 1,121 machines that exist at named
resorts. Repair records invented against them would be indistinguishable from
fact a year from now, so this module never runs unless explicitly asked:

    py -3.10 manage.py seed --only dummy
    py -3.10 manage.py reset --yes --with-history

The cost of that choice is visible and deliberate: without this step the repair
dashboard, the MCF curve and Laporan Perbaikan render EMPTY, because there is
genuinely no maintenance history to plot.

The 100 assets it creates carry their own condition, transfer and calibration
history, generated by a small state machine so the resulting curves look like
machinery rather than like noise.
"""

import random
from datetime import date, datetime

import models
from database import SessionLocal
from seed_katalog import ALL_ALAT
from seeds.katalog import get_parent_lokasi_code
from seeds.katalog import run as seed_katalog_run
from seeds.simulasi import SimContext, simulate_history

# A private Random instance rather than `random.seed()`, matching
# `seeds/inventaris.py`: seeding the global RNG reaches every other module in
# the process, and this one is imported by a CLI that also generates a bootstrap
# password. Fixing the stream makes `manage.py reset --with-history` reproducible
# two resets of the same database produce the same 100 machines with the same
# history, which is what lets the verification harness hold a baseline at all.
_DUMMY_RNG_SEED = 20260815
_rng = random.Random(_DUMMY_RNG_SEED)

# (ALAT_KODE_LIST was built here and never read; DUMMY_ALAT_SPREAD below is
#  what the generator actually walks.)

# The nine tool types the demo data is built from. Spreading 100 dummy assets
# across all 104 katalog codes would leave most types empty and none of them
# convincing.
DUMMY_ALAT_SPREAD = [
    "GEN", "PBT", "BOR", "IMP", "RGM", "TGT", "USM", "RFD", "TRG",
]

# Matches normalise_peruntukan() in main.py, a closed set, baked into the
# asset's composite primary key.
PERUNTUKAN_MAP = {
    "A": "JALAN REL",
    "B": "JEMBATAN",
    "C": "MEKANIK",
    "D": "BALAIYASA",
}
# (`PERUNTUKAN_LETTERS` stood here. It existed only so the state machine could
#  pick a letter at random, which is the bug the peruntukan rule fixed, since
#  the letter is DERIVED from the resort prefix. Nothing reads it now.)

SERI_PREFIX = {
    "GEN": "GEN", "PBT": "TMP", "BOR": "DRL", "IMP": "IWR", "RGM": "GRD",
    "TGT": "TGT", "USM": "USM", "RFD": "RFD", "TRG": "TRG",
}

# ── What marks an asset as fabricated ─────────────────────────────────
#
# Every asset this module creates carries a `nomor_seri` beginning `DEMO-`, and
# that prefix is load-bearing in two ways:
#
#   * it is the IDENTITY GATE. This step used to have none at all, so
#     `manage.py seed --only dummy --with-history` added 100 more assets every
#     time it ran, 1121 → 1221 → 1321. That is precisely the fleet-doubling bug
#     the whole `seeds/` package was written to eliminate, surviving in the one
#     step that never got the treatment. `existing_demo_count()` is the fix.
#   * it is honest. A nomor_seri is what a technician reads off a nameplate to
#     confirm they are holding the right machine. A fabricated one that RAMCES
#     presents in the same typeface as a real one is actively misleading in the
#     field, so a fabricated one says so.
#
# It must never be given to a workbook asset. `backfill_varian_dan_seri()` uses
# the plain per-tool prefixes for those, and only for assets that have no serial
# at all.
DEMO_SERI_PREFIX = "DEMO-"

# ── The peruntukan rule ───────────────────────────────────────────────
#
# A UPT code's prefix IS its peruntukan, verified 1:1 across all 254 rows of
# `KATALOG UPT`. This module used to pick a peruntukan letter at random,
# independently of where it had just placed the asset, which minted demo assets
# whose id_aset peruntukan segment contradicted their own resort: a `JALAN REL`
# machine sitting at `JB1.1`. Real assets have not been able to do that since
# the importer started deriving it, so the demo data was the only source of rows
# that broke the rule, and it broke it for roughly three quarters of them.
UPT_PREFIX_TO_LETTER = {"JR": "A", "JB": "B", "ME": "C", "BY": "D"}


def peruntukan_letter_for(id_lokasi: str) -> str:
    """
    The peruntukan letter a resort code implies.

    Falls back to `A` (JALAN REL) for a DAOP/DIVRE parent code, which carries no
    prefix, an asset homed directly at a parent rather than at one of its
    resorts is unusual but legal, and jalan rel is the overwhelming majority.
    """
    return UPT_PREFIX_TO_LETTER.get(str(id_lokasi or "")[:2].upper(), "A")


def existing_demo_count(db) -> int:
    """How many demo assets are already in the database."""
    return (
        db.query(models.Aset)
        .filter(models.Aset.nomor_seri.like(f"{DEMO_SERI_PREFIX}%"))
        .count()
    )

# `kalibrasi_alat_codes()` and the calibration constants moved to
# seeds/simulasi.py with the state machine that used them, only calibrated tool
# types get certificates, read from `kategori_alat.perlu_kalibrasi` rather than a
# hardcoded set, because a genset is serviced and not calibrated.

def _system_user(db):
    """The SUPER_ADMIN every seeded history row is attributed to."""
    user = db.query(models.Pengguna).first()
    if not user:
        user = models.Pengguna(
            username="SYSTEM", hashed_password=None, role="SUPER_ADMIN", id_lokasi=None
        )
        db.add(user)
        db.commit()
        db.refresh(user)
    return user


def generate_dummy_assets(total_count: int = 100):
    db = SessionLocal()
    try:
        # ── 0. The identity gate ─────────────────────────────────────────
        #
        # `total_count` is a TARGET POPULATION, not a number to add. Without
        # this, every invocation appended another full batch:
        #
        #     manage.py seed --only dummy --with-history   # aset 1121 -> 1221
        #     manage.py seed --only dummy --with-history   # aset 1221 -> 1321
        #
        # and `--verify` passed 11/11 both times, because its asset check was a
        # deliberately loose `expected <= n < expected * 2` range that leaves
        # room for eleven such runs before it complains. Both halves are fixed:
        # the shortfall below, and a separate demo/workbook count in
        # `seeds/verify.py`.
        already = existing_demo_count(db)
        if already >= total_count:
            print(
                f"  aset dummy    : {already} sudah ada (target {total_count}) — "
                "tidak ada yang ditambahkan."
            )
            return
        if already:
            print(
                f"  aset dummy    : {already} sudah ada, menambah "
                f"{total_count - already} untuk mencapai {total_count}."
            )
        total_count -= already

        # ── 1. Master data (alat kerja + lokasi + UPT) ───────────────────
        seed_katalog_run(db)
        db.commit()

        # ── 2. Lokasi ────────────────────────────────────────────────────
        # Lokasi.tipe values in the current model: PUSAT, DAOP, DIVRE, BALAIYASA, UPT
        # Parent lokasi = tipe in {DAOP, DIVRE, PUSAT, BALAIYASA}
        # Child  lokasi = tipe == UPT  (id_lokasi contains a dot, e.g. "JR1.1")
        all_lokasi = db.query(models.Lokasi).all()
        if not all_lokasi:
            raise ValueError(
                "Tabel 'lokasi' kosong. Isi master lokasi terlebih dahulu."
            )

        PARENT_TIPES = {"DAOP", "DIVRE", "PUSAT", "BALAIYASA"}

        balaiyasa_ids = [
            l.id_lokasi for l in all_lokasi
            if l.tipe.upper() == "BALAIYASA"
        ]

        # Operational = DAOP / DIVRE parents + their UPTs. Assets are HOMED here.
        #
        # Balaiyasa is a workshop, not an operating region: an asset may visit one
        # for repair but must never be based at one. The BY*A rows are typed
        # "UPT", so they have to be excluded explicitly, get_parent_lokasi_code
        # resolves them to a BY* parent, which is what identifies them.
        def _is_balaiyasa_side(id_lokasi: str) -> bool:
            if id_lokasi in balaiyasa_ids:
                return True
            parent = get_parent_lokasi_code(id_lokasi)
            return bool(parent) and parent in balaiyasa_ids

        operational_ids = [
            l.id_lokasi for l in all_lokasi
            if l.tipe.upper() in {"DAOP", "DIVRE", "UPT"}
            and not _is_balaiyasa_side(l.id_lokasi)
        ]
        # Fallback if classification is incomplete
        if not operational_ids:
            operational_ids = [l.id_lokasi for l in all_lokasi]

        # Build a quick lookup: id_lokasi → parent id (None if already a parent)
        # This is used to derive the parent_lokasi segment of the asset ID,
        # mirroring the logic in main.py's create_aset / update_aset.
        def derive_parent(id_lokasi: str) -> str:
            """Return the parent region code embedded in the asset ID."""
            parent = get_parent_lokasi_code(id_lokasi)
            if parent:
                return parent
            # Already a parent (no dot-separated suffix), use itself
            return id_lokasi

        # ── 3. Default Pengguna ──────────────────────────────────────────
        user = db.query(models.Pengguna).first()
        if not user:
            user = models.Pengguna(
                username="SYSTEM",
                hashed_password=None,
                role="SUPER_ADMIN",
                id_lokasi=None,
            )
            db.add(user)
            db.flush()
        id_pengguna_default = user.id_pengguna

        # ── 4. Distribute asset types evenly ─────────────────────────────
        # A representative spread rather than all 104 katalog codes: 100 dummy
        # assets over 104 tool types would give most types zero and none a
        # believable population.
        kode_alat_list = DUMMY_ALAT_SPREAD
        base = total_count // len(kode_alat_list)
        remainder = total_count % len(kode_alat_list)
        assigned = []
        for i, kode in enumerate(kode_alat_list):
            assigned.extend([kode] * (base + (1 if i < remainder else 0)))
        _rng.shuffle(assigned)

        # ── 5. Per-kode_alat sequence counter (mirrors main.py nomor_urut) ──
        # main.py counts existing assets of the same kode_alat and adds 1.
        # We track it locally so we don't hit the DB on every iteration.
        seq_counter: dict[str, int] = {}
        for kode in kode_alat_list:
            seq_counter[kode] = (
                db.query(models.Aset)
                .filter(models.Aset.kode_alat == kode)
                .count()
            )

        # ── 6. Seed assets ───────────────────────────────────────────────
        #
        # The history generator's context is built ONCE, it loads the lokasi
        # tree, the calibration flags and the whole stock balance map, none of
        # which vary per asset. It is given THIS module's RNG so a demo fleet
        # stays reproducible from the same seed.
        ctx = SimContext(db, rng=_rng, populasi=total_count)
        inserted = 0
        now = datetime.now()

        for kode_alat in assigned:
            # Pick a starting location (operational)
            start_lokasi = _rng.choice(operational_ids)

            # Must match the value the UI writes (index.html) exactly, a spaced
            # variant here silently breaks every Pengadaan filter in the app.
            sumber = _rng.choice(["PUSAT", "DAOP/DIVRE"])
            id_pengadaan = 1 if sumber == "PUSAT" else 2

            year_int = _rng.randint(2015, 2023)
            tgl_pembelian = date(year_int, _rng.randint(1, 12), _rng.randint(1, 28))
            year_str = str(year_int)[-2:]   # "15" … "23"

            # DERIVED from the resort code, never chosen. See the note on
            # UPT_PREFIX_TO_LETTER: the prefix IS the peruntukan, and a demo
            # asset that disagrees with its own resort is a row the real
            # importer can no longer produce.
            unit_letter = peruntukan_letter_for(start_lokasi)
            peruntukan = PERUNTUKAN_MAP[unit_letter]
            parent_lokasi = derive_parent(start_lokasi)

            # Build ID exactly like main.py's create_aset
            seq_counter[kode_alat] += 1
            nomor_urut = seq_counter[kode_alat]
            id_aset = f"{nomor_urut}.{kode_alat}.{id_pengadaan}.{year_str}.{unit_letter}.{parent_lokasi}"

            # Skip if the ID already exists (shouldn't happen on a clean DB)
            if db.query(models.Aset).filter_by(id_aset=id_aset).first():
                seq_counter[kode_alat] += 1
                nomor_urut = seq_counter[kode_alat]
                id_aset = f"{nomor_urut}.{kode_alat}.{id_pengadaan}.{year_str}.{unit_letter}.{parent_lokasi}"

            # ── State-machine simulation ─────────────────────────────────
            # Created SO at its starting resort; simulate_history() takes it
            # from there and derives home vs current position itself.
            waktu = datetime.combine(tgl_pembelian, datetime.min.time())
            lokasi_saat_ini = start_lokasi
            kondisi = "SO"

            aset = models.Aset(
                id_aset=id_aset,
                kode_alat=kode_alat,
                id_lokasi=lokasi_saat_ini,
                tanggal_pembelian=tgl_pembelian,
                sumber_pengadaan=sumber,
                status_terakhir=kondisi,
                waktu_update=waktu,
                peruntukan=peruntukan,
                # Stamped HERE, not by the backfill below, because it is what
                # makes this row recognisable as demo data on the next run. See
                # DEMO_SERI_PREFIX.
                nomor_seri=(
                    f"{DEMO_SERI_PREFIX}"
                    f"{SERI_PREFIX.get(kode_alat, kode_alat)}-"
                    f"{year_int}-{_rng.randint(10000, 99999)}"
                ),
            )
            db.add(aset)

            # Initial condition record, no id_lokasi column in RiwayatKondisi
            db.add(models.RiwayatKondisi(
                id_aset=id_aset,
                id_pengguna=id_pengguna_default,
                kondisi=kondisi,
                keterangan="Pencatatan aset baru",
                waktu_lapor=waktu,
                id_lokasi=lokasi_saat_ini,
                peruntukan=peruntukan,
            ))

            # ── The simulated history ────────────────────────────────
            #
            # EXTRACTED to seeds/simulasi.py, which the real fleet uses too.
            # This block used to live here, which is the only reason it ever ran
            # against the 100 demo assets and never against the 1,121 real ones.
            # It carries four rules that took three rounds to get right, the
            # Balaiyasa attribution rule, peruntukan-preserving redistribution,
            # calibration gated on the katalog flag, and the "never home an
            # asset at a workshop" safety net, and a second copy would have had
            # to keep all four in step.
            #
            # A consequence worth having: this history is now MARKED. It is just
            # as fabricated as the real fleet's would be, and until now was
            # indistinguishable from a technician's entry.
            simulate_history(ctx, aset, mulai=waktu)

            inserted += 1
            if inserted % 100 == 0:
                db.commit()
                print(f"Progress: {inserted}/{total_count} aset dimasukkan...")

        db.commit()
        print(f"Selesai! Total {inserted} aset dummy berhasil dibuat.")

    except Exception as e:
        db.rollback()
        print(f"Error saat generate dummy data: {e}")
        raise
    finally:
        db.close()


def backfill_varian_dan_seri(db):
    """
    Give every asset that still lacks one a Model/Type and a serial number.

    Moved here out of `seeds/inventaris.py`, where it ran against the WHOLE
    fleet. Both values are invented, and inventing them for a real machine is
    not a cosmetic problem:

      * a nomor_seri is what a technician reads off the nameplate to confirm
        they are looking at the right unit, so a fabricated one that RAMCES
        presents as fact is actively misleading in the field;
      * a Model/Type drives the sparepart compatibility filter, so a wrong one
        offers the wrong parts for the machine in front of them.

    The imported fleet gets its model from the workbook's own Model column, and
    a visibly-incomplete row when that cannot be resolved, which is the honest
    outcome. This function therefore runs ONLY as part of the dummy step.

    Demo assets no longer pass through the serial half of it: they are stamped
    `DEMO-…` at creation, because that prefix is the identity gate that stops a
    second run adding another hundred of them.
    """
    varian_by_alat = {}
    for v in db.query(models.AlatVarian).all():
        varian_by_alat.setdefault(v.kode_alat, []).append(v.id_varian)

    assigned = 0
    for aset in db.query(models.Aset).filter(models.Aset.id_varian.is_(None)).all():
        opts = varian_by_alat.get(aset.kode_alat)
        if opts:
            aset.id_varian = _rng.choice(opts)
            assigned += 1

    seri = 0
    for aset in db.query(models.Aset).filter(models.Aset.nomor_seri.is_(None)).all():
        prefix = SERI_PREFIX.get(aset.kode_alat, aset.kode_alat)
        tahun = aset.tanggal_pembelian.year if aset.tanggal_pembelian else 2020
        aset.nomor_seri = f"{prefix}-{tahun}-{_rng.randint(10000, 99999)}"
        seri += 1
    db.commit()
    print(f"  backfill      : {assigned} Model/Type, {seri} nomor seri (data contoh)")


def run(db, total_aset: int = 100):
    """Registry entry point. generate_dummy_assets opens its own session."""
    generate_dummy_assets(total_aset)
    backfill_varian_dan_seri(db)
