"""
Synthetic demo assets and a simulated maintenance history.

OFF BY DEFAULT, and that is the whole point. The fleet imported from
`Template_Import_Aset_RAMCES.xlsx` is REAL — 1,121 machines that exist at named
resorts. Repair records invented against them would be indistinguishable from
fact a year from now, so this module never runs unless explicitly asked:

    py -3.10 seed.py --only dummy
    py -3.10 reset.py --yes --with-history

The cost of that choice is visible and deliberate: without this step the repair
dashboard, the MCF curve and Laporan Perbaikan render EMPTY, because there is
genuinely no maintenance history to plot.

The 100 assets it creates carry their own condition, transfer and calibration
history, generated by a small state machine so the resulting curves look like
machinery rather than like noise.
"""

import random
from datetime import date, datetime, timedelta

import models
from database import SessionLocal
from seed_katalog import ALL_ALAT
from seeds.katalog import get_parent_lokasi_code
from seeds.katalog import run as seed_katalog_run

# (ALAT_KODE_LIST was built here and never read; DUMMY_ALAT_SPREAD below is
#  what the generator actually walks.)

# The nine tool types the demo data is built from. Spreading 100 dummy assets
# across all 104 katalog codes would leave most types empty and none of them
# convincing.
DUMMY_ALAT_SPREAD = [
    "GEN", "PBT", "BOR", "IMP", "RGM", "TGT", "USM", "RFD", "TRG",
]

# Matches normalise_peruntukan() in main.py — a closed set, baked into the
# asset's composite primary key.
PERUNTUKAN_MAP = {
    "A": "JALAN REL",
    "B": "JEMBATAN",
    "C": "MEKANIK",
    "D": "BALAIYASA",
}
PERUNTUKAN_LETTERS = list(PERUNTUKAN_MAP.keys())

SERI_PREFIX = {
    "GEN": "GEN", "PBT": "TMP", "BOR": "DRL", "IMP": "IWR", "RGM": "GRD",
    "TGT": "TGT", "USM": "USM", "RFD": "RFD", "TRG": "TRG",
}

# Only MEASURING instruments get calibrated. A genset or an impact wrench is
# serviced, not calibrated, so seeding certificates for them would be fiction.
# Read from the katalog flag rather than a hardcoded set, so seeded data and the
# live UI gate (kategori_alat.perlu_kalibrasi) cannot disagree.
def kalibrasi_alat_codes(db) -> set:
    return {
        row[0]
        for row in db.query(models.KategoriAlat.kode_alat)
        .filter(models.KategoriAlat.perlu_kalibrasi.is_(True))
        .all()
    }

PELAKSANA_KALIBRASI = [
    "BALAI KALIBRASI KAI",
    "PT KAI BALAI YASA",
    "LAB METROLOGI BANDUNG",
    "BSN - KAN TERAKREDITASI",
]

KALIBRASI_KETERANGAN = {
    "LULUS": "Hasil kalibrasi sesuai toleransi.",
    "BERSYARAT": "Deviasi kecil, layak pakai dengan pemantauan.",
    "GAGAL": "Deviasi melebihi ambang; perlu perbaikan/kalibrasi ulang.",
}


def _system_user(db):
    """The SUPER_ADMIN every seeded history row is attributed to."""
    user = db.query(models.Pengguna).first()
    if not user:
        user = models.Pengguna(
            username="SYSTEM", hashed_password=None, role="SUPER_ADMIN", id_lokasi=None
        )
        db.add(user)
        db.commit()
        db.refresh(user)
    return user


def generate_dummy_assets(total_count: int = 100):
    db = SessionLocal()
    try:

        # ── 1. Master data (alat kerja + lokasi + UPT) ───────────────────
        seed_katalog_run(db)
        db.commit()
        # Which tool types actually get calibrated, straight from the katalog
        # flag rather than a hardcoded guess.
        kalibrasi_codes = kalibrasi_alat_codes(db)

        # ── 2. Lokasi ────────────────────────────────────────────────────
        # Lokasi.tipe values in the current model: PUSAT, DAOP, DIVRE, BALAIYASA, UPT
        # Parent lokasi = tipe in {DAOP, DIVRE, PUSAT, BALAIYASA}
        # Child  lokasi = tipe == UPT  (id_lokasi contains a dot, e.g. "JR1.1")
        all_lokasi = db.query(models.Lokasi).all()
        if not all_lokasi:
            raise ValueError(
                "Tabel 'lokasi' kosong. Isi master lokasi terlebih dahulu."
            )

        PARENT_TIPES = {"DAOP", "DIVRE", "PUSAT", "BALAIYASA"}

        parent_lokasi_ids = [
            l.id_lokasi for l in all_lokasi
            if l.tipe.upper() in PARENT_TIPES
        ]
        upt_lokasi_ids = [
            l.id_lokasi for l in all_lokasi
            if l.tipe.upper() == "UPT"
        ]
        balaiyasa_ids = [
            l.id_lokasi for l in all_lokasi
            if l.tipe.upper() == "BALAIYASA"
        ]

        # Operational = DAOP / DIVRE parents + their UPTs. Assets are HOMED here.
        #
        # Balaiyasa is a workshop, not an operating region: an asset may visit one
        # for repair but must never be based at one. The BY*A rows are typed
        # "UPT", so they have to be excluded explicitly — get_parent_lokasi_code
        # resolves them to a BY* parent, which is what identifies them.
        def _is_balaiyasa_side(id_lokasi: str) -> bool:
            if id_lokasi in balaiyasa_ids:
                return True
            parent = get_parent_lokasi_code(id_lokasi)
            return bool(parent) and parent in balaiyasa_ids

        operational_ids = [
            l.id_lokasi for l in all_lokasi
            if l.tipe.upper() in {"DAOP", "DIVRE", "UPT"}
            and not _is_balaiyasa_side(l.id_lokasi)
        ]
        # Workshop / bengkel = BALAIYASA entries (TSO assets get sent here)
        bengkel_ids = balaiyasa_ids if balaiyasa_ids else parent_lokasi_ids

        # Fallback if classification is incomplete
        if not operational_ids:
            operational_ids = [l.id_lokasi for l in all_lokasi]

        # Build a quick lookup: id_lokasi → parent id (None if already a parent)
        # This is used to derive the parent_lokasi segment of the asset ID,
        # mirroring the logic in main.py's create_aset / update_aset.
        def derive_parent(id_lokasi: str) -> str:
            """Return the parent region code embedded in the asset ID."""
            parent = get_parent_lokasi_code(id_lokasi)
            if parent:
                return parent
            # Already a parent (no dot-separated suffix) — use itself
            return id_lokasi

        # ── 3. Default Pengguna ──────────────────────────────────────────
        user = db.query(models.Pengguna).first()
        if not user:
            user = models.Pengguna(
                username="SYSTEM",
                hashed_password=None,
                role="SUPER_ADMIN",
                id_lokasi=None,
            )
            db.add(user)
            db.flush()
        id_pengguna_default = user.id_pengguna

        # ── 4. Distribute asset types evenly ─────────────────────────────
        # A representative spread rather than all 104 katalog codes: 100 dummy
        # assets over 104 tool types would give most types zero and none a
        # believable population.
        kode_alat_list = DUMMY_ALAT_SPREAD
        base = total_count // len(kode_alat_list)
        remainder = total_count % len(kode_alat_list)
        assigned = []
        for i, kode in enumerate(kode_alat_list):
            assigned.extend([kode] * (base + (1 if i < remainder else 0)))
        random.shuffle(assigned)

        # ── 5. Per-kode_alat sequence counter (mirrors main.py nomor_urut) ──
        # main.py counts existing assets of the same kode_alat and adds 1.
        # We track it locally so we don't hit the DB on every iteration.
        seq_counter: dict[str, int] = {}
        for kode in kode_alat_list:
            seq_counter[kode] = (
                db.query(models.Aset)
                .filter(models.Aset.kode_alat == kode)
                .count()
            )

        # ── 6. Seed assets ───────────────────────────────────────────────
        inserted = 0
        now = datetime.now()

        for kode_alat in assigned:
            # Pick a starting location (operational)
            start_lokasi = random.choice(operational_ids)

            # Must match the value the UI writes (index.html) exactly — a spaced
            # variant here silently breaks every Pengadaan filter in the app.
            sumber = random.choice(["PUSAT", "DAOP/DIVRE"])
            id_pengadaan = 1 if sumber == "PUSAT" else 2

            year_int = random.randint(2015, 2023)
            tgl_pembelian = date(year_int, random.randint(1, 12), random.randint(1, 28))
            year_str = str(year_int)[-2:]   # "15" … "23"

            unit_letter = random.choice(PERUNTUKAN_LETTERS)
            peruntukan = PERUNTUKAN_MAP[unit_letter]
            parent_lokasi = derive_parent(start_lokasi)

            # Build ID exactly like main.py's create_aset
            seq_counter[kode_alat] += 1
            nomor_urut = seq_counter[kode_alat]
            id_aset = f"{nomor_urut}.{kode_alat}.{id_pengadaan}.{year_str}.{unit_letter}.{parent_lokasi}"

            # Skip if the ID already exists (shouldn't happen on a clean DB)
            if db.query(models.Aset).filter_by(id_aset=id_aset).first():
                seq_counter[kode_alat] += 1
                nomor_urut = seq_counter[kode_alat]
                id_aset = f"{nomor_urut}.{kode_alat}.{id_pengadaan}.{year_str}.{unit_letter}.{parent_lokasi}"

            # ── State-machine simulation ─────────────────────────────────
            waktu = datetime.combine(tgl_pembelian, datetime.min.time())
            lokasi_saat_ini = start_lokasi
            # Where the asset BELONGS, as opposed to where it currently sits. A
            # workshop visit changes the latter but never the former.
            home_lokasi = start_lokasi
            kondisi = "SO"

            aset = models.Aset(
                id_aset=id_aset,
                kode_alat=kode_alat,
                id_lokasi=lokasi_saat_ini,
                tanggal_pembelian=tgl_pembelian,
                sumber_pengadaan=sumber,
                status_terakhir=kondisi,
                waktu_update=waktu,
                peruntukan=peruntukan,
            )
            db.add(aset)

            # Initial condition record — no id_lokasi column in RiwayatKondisi
            db.add(models.RiwayatKondisi(
                id_aset=id_aset,
                id_pengguna=id_pengguna_default,
                kondisi=kondisi,
                keterangan="Pencatatan aset baru",
                waktu_lapor=waktu,
                id_lokasi=lokasi_saat_ini,
                peruntukan=peruntukan,
            ))

            # Random lifecycle events (0–15 per asset)
            for _ in range(random.randint(0, 15)):
                waktu += timedelta(days=random.randint(14, 120), hours=random.randint(1, 23))
                if waktu > now:
                    break

                if kondisi == "AFKIR":
                    break

                elif kondisi == "TSO":
                    is_bengkel = lokasi_saat_ini in bengkel_ids
                    if not is_bengkel and bengkel_ids:
                        # Send to workshop
                        tujuan = random.choice(bengkel_ids)
                        db.add(models.RiwayatMutasi(
                            id_aset=id_aset,
                            id_lokasi_asal=lokasi_saat_ini,
                            id_lokasi_tujuan=tujuan,
                            id_pengguna=id_pengguna_default,
                            alasan_mutasi="Pengiriman untuk perbaikan (TSO)",
                            waktu_mutasi=waktu,
                        ))
                        lokasi_saat_ini = tujuan
                    else:
                        # Repair outcome
                        kondisi = random.choices(["SO", "AFKIR"], weights=[90, 10])[0]
                        db.add(models.RiwayatKondisi(
                            id_aset=id_aset,
                            id_pengguna=id_pengguna_default,
                            kondisi=kondisi,
                            keterangan=f"Hasil perbaikan: {kondisi}",
                            waktu_lapor=waktu,
                            # NOT lokasi_saat_ini. The repair physically happens
                            # at a Balaiyasa, but it belongs to the region that
                            # owns the asset. Stamping the workshop here is what
                            # used to grow a "BALAIYASA …" row in Laporan
                            # Perbaikan and drop the completion out of the
                            # owning DAOP's scope, so `masuk` never reconciled
                            # against `selesai + sedang`. The mutation rows
                            # above still record the physical trip.
                            id_lokasi=home_lokasi,
                            peruntukan=peruntukan,
                        ))
                        # A repaired asset goes back to its operating resort. Without
                        # this it would stay parked at the Balaiyasa forever, and the
                        # final write-back would home it at a workshop.
                        if kondisi == "SO" and lokasi_saat_ini != home_lokasi:
                            waktu += timedelta(days=random.randint(1, 10))
                            db.add(models.RiwayatMutasi(
                                id_aset=id_aset,
                                id_lokasi_asal=lokasi_saat_ini,
                                id_lokasi_tujuan=home_lokasi,
                                id_pengguna=id_pengguna_default,
                                alasan_mutasi="Pengembalian setelah perbaikan",
                                waktu_mutasi=waktu,
                            ))
                            lokasi_saat_ini = home_lokasi

                elif kondisi == "SO":
                    aksi = random.choices(["MUTASI", "KONDISI"], weights=[30, 70])[0]
                    if aksi == "MUTASI" and len(operational_ids) > 1:
                        tujuan = random.choice(operational_ids)
                        while tujuan == lokasi_saat_ini:
                            tujuan = random.choice(operational_ids)
                        db.add(models.RiwayatMutasi(
                            id_aset=id_aset,
                            id_lokasi_asal=lokasi_saat_ini,
                            id_lokasi_tujuan=tujuan,
                            id_pengguna=id_pengguna_default,
                            alasan_mutasi="Redistribusi operasional",
                            waktu_mutasi=waktu,
                        ))
                        lokasi_saat_ini = tujuan
                        # A redistribution is a permanent move — this is now home.
                        home_lokasi = tujuan
                    else:
                        kondisi = random.choices(["TSO", "AFKIR"], weights=[85, 15])[0]
                        db.add(models.RiwayatKondisi(
                            id_aset=id_aset,
                            id_pengguna=id_pengguna_default,
                            kondisi=kondisi,
                            keterangan=f"Degradasi kondisi ke {kondisi}",
                            waktu_lapor=waktu,
                            # Same rule as the repair-outcome row: condition
                            # history is attributed to the owning region, never
                            # to a workshop the asset is merely visiting.
                            id_lokasi=home_lokasi,
                            peruntukan=peruntukan,
                        ))

            # ── Periodic calibration history ─────────────────────────────
            # Measuring tools are recalibrated roughly yearly. Without these
            # rows the Kalibrasi card grid, the asset detail tab and the
            # Kalibrasi export are all permanently empty.
            if kode_alat in kalibrasi_codes:
                kal_tanggal = tgl_pembelian
                while True:
                    kal_tanggal = kal_tanggal + timedelta(days=random.randint(330, 400))
                    if kal_tanggal >= now.date():
                        break
                    status_kal = random.choices(
                        ["LULUS", "BERSYARAT", "GAGAL"], weights=[80, 15, 5]
                    )[0]
                    db.add(models.RiwayatKalibrasi(
                        id_aset=id_aset,
                        id_pengguna=id_pengguna_default,
                        tanggal_kalibrasi=kal_tanggal,
                        tanggal_berlaku=kal_tanggal + timedelta(days=365),
                        status=status_kal,
                        pelaksana_kalibrasi=random.choice(PELAKSANA_KALIBRASI),
                        nomor_sertifikat=(
                            f"KAL/{kal_tanggal.year}/"
                            f"{random.randint(1000, 9999)}"
                        ),
                        keterangan=KALIBRASI_KETERANGAN[status_kal],
                        waktu_input=datetime.combine(
                            kal_tanggal, datetime.min.time()
                        ),
                    ))

            # Write final state back to the asset row.
            # Safety net: an asset must never be HOMED at a workshop. If the
            # simulation ended mid-repair at a Balaiyasa we keep the condition
            # (it really is under repair) but record its owning resort.
            aset.status_terakhir = kondisi
            aset.id_lokasi = (
                home_lokasi if _is_balaiyasa_side(lokasi_saat_ini) else lokasi_saat_ini
            )
            aset.waktu_update = waktu

            inserted += 1
            if inserted % 100 == 0:
                db.commit()
                print(f"Progress: {inserted}/{total_count} aset dimasukkan...")

        db.commit()
        print(f"Selesai! Total {inserted} aset dummy berhasil dibuat.")

    except Exception as e:
        db.rollback()
        print(f"Error saat generate dummy data: {e}")
        raise
    finally:
        db.close()


def backfill_varian_dan_seri(db):
    """
    Give every asset that still lacks one a Model/Type and a serial number.

    Moved here out of `seeds/inventaris.py`, where it ran against the WHOLE
    fleet. Both values are invented, and inventing them for a real machine is
    not a cosmetic problem:

      * a nomor_seri is what a technician reads off the nameplate to confirm
        they are looking at the right unit, so a fabricated one that RAMCES
        presents as fact is actively misleading in the field;
      * a Model/Type drives the sparepart compatibility filter, so a wrong one
        offers the wrong parts for the machine in front of them.

    The imported fleet gets its model from the workbook's own Model column, and
    a visibly-incomplete row when that cannot be resolved — which is the honest
    outcome. This function therefore runs ONLY as part of the dummy step.
    """
    varian_by_alat = {}
    for v in db.query(models.AlatVarian).all():
        varian_by_alat.setdefault(v.kode_alat, []).append(v.id_varian)

    assigned = 0
    for aset in db.query(models.Aset).filter(models.Aset.id_varian.is_(None)).all():
        opts = varian_by_alat.get(aset.kode_alat)
        if opts:
            aset.id_varian = random.choice(opts)
            assigned += 1

    seri = 0
    for aset in db.query(models.Aset).filter(models.Aset.nomor_seri.is_(None)).all():
        prefix = SERI_PREFIX.get(aset.kode_alat, aset.kode_alat)
        tahun = aset.tanggal_pembelian.year if aset.tanggal_pembelian else 2020
        aset.nomor_seri = f"{prefix}-{tahun}-{random.randint(10000, 99999)}"
        seri += 1
    db.commit()
    print(f"  backfill      : {assigned} Model/Type, {seri} nomor seri (data contoh)")


def run(db, total_aset: int = 100):
    """Registry entry point. generate_dummy_assets opens its own session."""
    generate_dummy_assets(total_aset)
    backfill_varian_dan_seri(db)
